name: Python Package

on:
  push:
    branches:
      - master
      - unstable
  pull_request:
    branches:
      - master
      - unstable

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }} and ${{ matrix.os }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./src/requirements.txt
        
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings.
        flake8 . --count --exit-zero --max-complexity=100 --max-line-length=200 --statistics
        
    - name: Build and install the pypi package
      run: |
        # build 
        python setup.py sdist
        # install 
        PKG_VERSION=`cat src/ea/VERSION`
        pip install ./dist/extensiveautomation_server-${PKG_VERSION}.tar.gz
        
    - name: Start the server
      run: |
        # start the server
        extensiveautomation --start
        # status the server
        extensiveautomation --status
        # install plugin web
        pip install extensiveautomation_plugin_web
        # reload server configuration
        extensiveautomation --reload
        
    - name: Test the server
      run: |
        # start to test the server
        python -u ./tests/test_server.py
